### PR TITLE
Add http header support

### LINKED ISSUE #33: Adding basic access authentication
Is it doable to add support for websites using basic access authentication?. This is goint to be helpful for web services as well.
Bascially, we need to add username/password per monitored component:

``` json
{
 //other settings,
"username": "someone",
"password": "somepass"
}
```

### PR DESCRIPTION
**Pull request by to-kn**
Add http-header Support, fixes #33

### CODE REVIEW

**Comment by dmsimard** [comment]
Would love to see this go in !

**Comment by matejkramny** [comment]
👍 good work. This will go in.

Both will be merged & released (this & #31) along with #38 in a couple of days.

If you want to skip the wait, you can fork & build yourself.

**Comment by wsoula** [comment]
What's the ETA on getting this merged and released?  I'd really like to use this functionality and am having issues trying to figure out how to build the project.

**Comment by matejkramny** [comment]
sorry for the delay.

The work will appear in the next version of this project.

**Pull request merged**
